# Load order matters: later files can override earlier settings.
source = ~/.config/mango/conf.d/env.conf
source = ~/.config/mango/conf.d/input.conf
source = ~/.config/mango/conf.d/layout.conf
source = ~/.config/mango/conf.d/appearance.conf
source = ~/.config/mango/noctalia.conf
source = ~/.config/mango/conf.d/monitors.conf
source = ~/.config/mango/conf.d/autostart.conf
source = ~/.config/mango/conf.d/keybinds.conf
source = ~/.config/mango/conf.d/mouse.conf
source = ~/.config/mango/conf.d/rules.conf
