# Theme colors sourced after appearance.conf.
shadowscolor = 0x000000ff
rootcolor = 0x191d24ff
bordercolor = 0x5b6880ff
focuscolor = 0xebcb8bff
maximizescreencolor = 0x81a1c1ff
urgentcolor = 0xc5727aff
scratchpadcolor = 0xb48eadff
globalcolor = 0xb57e0eff
overlaycolor = 0x25486bff
