# Keyboard and pointer behavior.
xkb_rules_layout = us

tap_to_click = 1
tap_and_drag = 1
drag_lock = 1
disable_while_typing = 1
mouse_natural_scrolling = 0
trackpad_natural_scrolling = 0

axis_scroll_factor = 3.0

# Move the pointer with keyboard focus changes.
warpcursor = 1
