# Applications.
bind = SUPER, b, spawn, zen-browser
bind = SUPER, t, spawn, ghostty
bind = SUPER, i, spawn, thunar
bind = SUPER, o, spawn, ghostty -e btop

# Launchers and tools.
bind = SUPER, p, spawn, fuzzel
bind = SUPER+SHIFT, m, spawn, ~/.config/wlogout/launch.sh
bind = SUPER+SHIFT, w, spawn, ~/.config/waybar/scripts/wallpaper.sh random
bind = SUPER+SHIFT, p, spawn, ~/.config/mango/scripts/screenshot.sh
bind = SUPER+SHIFT, r, reload_config

# Workspaces.
bind = SUPER, q, view, 1, 0
bind = SUPER, w, view, 2, 0
bind = SUPER, e, view, 3, 0
bind = SUPER, r, view, 4, 0

# Focus movement.
bind = SUPER, d, spawn, ~/.config/mango/scripts/cycle-master.sh next
bind = SUPER, a, spawn, ~/.config/mango/scripts/cycle-master.sh prev
bind = SUPER, s, zoom,
bind = SUPER, h, focusdir, left
bind = SUPER, j, focusdir, down
bind = SUPER, k, focusdir, up
bind = SUPER, l, focusdir, right

# Master-stack layout.
bind = SUPER+SHIFT, minus, setmfact, -0.05
bind = SUPER+SHIFT, equal, setmfact, +0.05
# bind = SUPER+SHIFT, minus, incnmaster, -1
# bind = SUPER+SHIFT, equal, incnmaster, +1

# Window actions.
bind = SUPER, m, killclient,force
bind = SUPER, f, togglemaximizescreen,
